[package]
name = "grams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
reqwest = {version = "0.12.4", features = ["blocking"]}
select = "0.6.0"
scraper = "0.19.0"